// Code generated by "stringer -type=StatusLineKind"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusLineKindIgnored-0]
	_ = x[StatusLineKindUntracked-1]
	_ = x[StatusLineKindComment-2]
	_ = x[StatusLineKindChanged-3]
	_ = x[StatusLineKindRenamedOrCopied-4]
	_ = x[StatusLineKindUnmerged-5]
}

const _StatusLineKind_name = "StatusLineKindIgnoredStatusLineKindUntrackedStatusLineKindCommentStatusLineKindChangedStatusLineKindRenamedOrCopiedStatusLineKindUnmerged"

var _StatusLineKind_index = [...]uint8{0, 21, 44, 65, 86, 115, 137}

func (i StatusLineKind) String() string {
	if i < 0 || i >= StatusLineKind(len(_StatusLineKind_index)-1) {
		return "StatusLineKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusLineKind_name[_StatusLineKind_index[i]:_StatusLineKind_index[i+1]]
}
