// Code generated by "stringer -type=ChangeKind"; DO NOT EDIT.

package orto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangeKindAdded-0]
	_ = x[ChangeKindDeleted-1]
	_ = x[ChangeKindUnchanged-2]
	_ = x[ChangeKindModified-3]
	_ = x[ChangeKindIgnoredByGit-4]
	_ = x[ChangeKindIgnoredByOrto-5]
}

const _ChangeKind_name = "ChangeKindAddedChangeKindDeletedChangeKindUnchangedChangeKindModifiedChangeKindIgnoredByGitChangeKindIgnoredByOrto"

var _ChangeKind_index = [...]uint8{0, 15, 32, 51, 69, 91, 114}

func (i ChangeKind) String() string {
	if i < 0 || i >= ChangeKind(len(_ChangeKind_index)-1) {
		return "ChangeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeKind_name[_ChangeKind_index[i]:_ChangeKind_index[i+1]]
}
