// Code generated by "stringer -type=ChangeKind"; DO NOT EDIT.

package orto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddedKind-0]
	_ = x[DeletedKind-1]
	_ = x[UnchangedKind-2]
	_ = x[ModifiedKind-3]
	_ = x[IgnoredByGitKind-4]
	_ = x[IgnoredByOrtoKind-5]
}

const _ChangeKind_name = "AddedKindDeletedKindUnchangedKindModifiedKindIgnoredByGitKindIgnoredByOrtoKind"

var _ChangeKind_index = [...]uint8{0, 9, 20, 33, 45, 61, 78}

func (i ChangeKind) String() string {
	if i < 0 || i >= ChangeKind(len(_ChangeKind_index)-1) {
		return "ChangeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeKind_name[_ChangeKind_index[i]:_ChangeKind_index[i+1]]
}
